services:
  flask:
    build: .
    volumes:
      - ./e_commerce_api:/app
        # - .:/app
    ports:
      - "8000:8000"
    command: flask run --host 0.0.0.0 --port 8000
    environment:
      FLASK_APP: app/app.py
  ffmpeg:
    build: ffmpeg/.
    command: ffmpeg -i assets/sr.mp4 assets/sr1.m2v
    volumes:
    - ./ffmpeg:/assets